spring.application.name=just-eat-backend

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/justeatdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
server.servlet.context-path=/api

# JWT configuration
jwt.secret=justeat_super_secret_key_which_is_at_least_32_chars_long!
jwt.expiration=3600000
